- modules/virtual-machine/README.md
> Fix readme

- LICENSE
https://www.apache.org/licenses/LICENSE-2.0
see
https://github.com/GoogleCloudPlatform/Template/blob/master/LICENSE
> #61 - add apache 2.0 LICENSE

- docs/README.md
- docs/google-cloud-onboarding.md
Will re-upload screencaps for this repo
> #87 - add onboarding wiki - cloud identity options 3/5

- docs/google-cloud-onboarding.md
verify screencaps move over to the base account
> #100 - add scenario 1: workspaces and gcp domain

- docs/automation/security_controls_services_automation_mappings.csv
- docs/google-cloud-security-controls.md
starting grid for security controls mapping/evidence
> #2 - grid for controls/service mapping

- docs/google-cloud-landingzone-traffic-generation.md
testing on alternate.gcp.zone
https://github.com/obrienlabs/magellan/issues/25
> #100 - traffic generation cli

- environments/common/common.auto.tfvars
- modules/organization-policy/locals.tf
See test results in https://github.com/canada-ca/accelerators_accelerateurs-gcp/pull/60
> #205 - disable public marketplace org policy - ready for review

- environments/bootstrap/terraform.tf
- modules/cloudbuild/templates/cloudbuild-pull-request.yaml
- modules/cloudbuild/templates/cloudbuild-push-request.yaml
See https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/224
for details and test results working around the removal of experimental optional() attributes
> #224 - workaround TF 1.3.7 from 1.0.10

- environments/nonprod/main.tf
- modules/20-partner-interconnect/main.tf
- modules/20-partner-interconnect/outputs.tf
Test results in 
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/249#issuecomment-1648251732
> #249 - enable 4 interconnects connected to single router

- environments/nonprod/main.tf
- environments/nonprod/nonp-interconnect.auto.tfvars
- environments/nonprod/variables.tf
- modules/20-partner-interconnect/main.tf
- modules/20-partner-interconnect/variables.tf
Test results
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/249#issuecomment-1649923189
> #249 - parameterize interconnect router name - remove derived vars

- environments/nonprod/main.tf
- environments/prod/main.tf
- environments/prod/prod-interconnect.auto.tfvars
- environments/prod/variables.tf
test results in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/249#issuecomment-1649968371
Add prod
```
root_@cloudshell:~/lz-tls/_lz2/pbmm-on-gcp-onboarding (lz-tls)$ git status
On branch main
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
new file:   environments/prod/prod-interconnect.auto.tfvars
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   environments/prod/main.tf
modified:   environments/prod/variables.tf
Step #3 - "tf plan": Plan: 5 to add, 2 to change, 0 to destroy.
Step #4 - "tf apply": *************** TERRAFORM APPLY ******************
Step #4 - "tf apply": ******* At environment: environments/prod …
```
> #249 - add prod interconnect/router

- environments/common/outputs.tf
- environments/prod/main.tf
- environments/prod/prod-workload-network.auto.tfvars
- environments/prod/variables.tf
> #263 - add workload services project off prod host project shared VPC

- environments/common/outputs.tf
- environments/prod/workloads.tf
Test results: common and prod cloud build
align levels 1 to levels 2 from level 2
> #263 - workloads folder level 2 to levels alignment

- environments/common/iam-groups.auto.tfvars
- environments/common/iam-groups.tf
- environments/common/variables.tf
> #271 - add iam group role assignment

- modules/20-partner-interconnect/main.tf
> #295 - add DNS Egress Proxy custom route to IC router

- environments/prod/dns.tf
> #293 - fix DNS forwarding 2nd IP

- environments/prod/prod-network.auto.tfvars
- environments/prod/psc.tf
- modules/22-private-service-connect/README.md
- modules/22-private-service-connect/dns.tf
- modules/22-private-service-connect/main.tf
- modules/22-private-service-connect/outputs.tf
- modules/22-private-service-connect/variables.tf
- modules/22-private-service-connect/versions.tf
Regional endpoint is in PR2
see test results in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/299
> #299 - Initial version of private service connect - with global endpoint

- environments/prod/main.tf
- environments/prod/prod-interconnect.auto.tfvars
- environments/prod/psc.tf
- environments/prod/variables.tf
- modules/20-partner-interconnect/main.tf
- modules/20-partner-interconnect/variables.tf
see test results in https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/299#issuecomment-1708309102
> #299 - add PSC IP to router advertisements

- environments/common/common.auto.tfvars
- environments/common/main.tf
- environments/common/variables.tf
- modules/audit-bunker/main.tf
- modules/audit-bunker/variables.tf
> #284 - move hardcoded audit services out of the module

- environments/common/common.auto.tfvars
- environments/common/main.tf
- environments/common/variables.tf
- modules/guardrails/main.tf
- modules/guardrails/variables.tf
test results in the issue at comment
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/284#issuecomment-1722616955
> #284 - refactor module guardrails hardcoded services list to env

- modules/budgets-alerts/README.md
- modules/budgets-alerts/examples/main.tf
- modules/budgets-alerts/main.tf
- modules/budgets-alerts/outputs.tf
- modules/budgets-alerts/terraform.tf
- modules/budgets-alerts/variables.tf
This is a module for creating budgets and alerts for the projects within the GCP.
> #330-Budgets and Alerts Module Added

- README.md
- Added more detailed step-by-step instructions.
- Improved the organization and formatting for clarity.
> #335 - Modified Readme

- 2024_fortigate-accelerator/README-fortigate-tutorial-gcp.md
- 2024_fortigate-accelerator/service_account_create.sh
- 2024_fortigate-accelerator/terraform/day0/main.tf
- 2024_fortigate-accelerator/terraform/day1/versions.tf
- 2024_fortigate-accelerator/terraform/modules/fgcp-ha-ap-lb/main.tf
> #345 - fix terraform fortigate-tutorial - quota, byod image, incoming 0.0.0.0/0 ACL, fortios authentication

- 0-bootstrap/outputs.tf.local
- 0-bootstrap/terraform.mod.tfvars
- 3-networks-hub-and-spoke/modules/transitivity/main.tf
Changes in 3 more files forgotten in PR#384
> Pr mro bootstrap run terraform local 041724 - missed some fixes

- README.md
CB/CSR returned as default for the main branch 
see #421 testing
> #421 - main branch defaults to CB/CSR

- 0-bootstrap/README.md
see testing in #360, #421 and #432
> #432 - cloudidentity googleapis enable

- 6-org-policies/readme.md
Added the newly updated 6-org-policy Readme file.
> Updated 6-org-policy readme.md
